package com.iwaliner.urushi.registries;

import com.iwaliner.urushi.ModCoreUrushi;
import com.iwaliner.urushi.common.entiity.*;
import com.iwaliner.urushi.common.entiity.food.*;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class EntityRegister {
    public static final DeferredRegister<EntityType<?>> Entities = DeferredRegister.create(BuiltInRegistries.ENTITY_TYPE, ModCoreUrushi.ModID);
    public static final DeferredHolder<EntityType<?>,EntityType<RiceFoodEntity>> RiceFoodEntity=Entities.register("rice_food", () -> EntityType.Builder.<RiceFoodEntity>of(RiceFoodEntity::new, MobCategory.MISC).sized(0.4F, 0.4F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"rice_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<TKGFoodEntity>> TKGFoodEntity=Entities.register("tkg_food", () -> EntityType.Builder.<TKGFoodEntity>of(TKGFoodEntity::new, MobCategory.MISC).sized(0.4F, 0.4F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"tkg_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<SekihanFoodEntity>> SekihanFoodEntity=Entities.register("sekihan_food", () -> EntityType.Builder.<SekihanFoodEntity>of(SekihanFoodEntity::new, MobCategory.MISC).sized(0.4F, 0.4F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"sekihan_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<GyudonFoodEntity>> GyudonFoodEntity=Entities.register("gyudon_food", () -> EntityType.Builder.<GyudonFoodEntity>of(GyudonFoodEntity::new, MobCategory.MISC).sized(0.4F, 0.4F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"gyudon_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<ButadonFoodEntity>> ButadonFoodEntity=Entities.register("butadon_food", () -> EntityType.Builder.<ButadonFoodEntity>of(ButadonFoodEntity::new, MobCategory.MISC).sized(0.4F, 0.4F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"butadon_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<KitsuneUdonFoodEntity>> KitsuneUdonFoodEntity=Entities.register("kitsune_udon_food", () -> EntityType.Builder.<KitsuneUdonFoodEntity>of(KitsuneUdonFoodEntity::new, MobCategory.MISC).sized(0.4F, 0.4F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"kitsune_udon_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<KaraageFoodEntity>> KaraageFoodEntity=Entities.register("karaage_food", () -> EntityType.Builder.<KaraageFoodEntity>of(KaraageFoodEntity::new, MobCategory.MISC).sized(0.6F, 0.6F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"karaage_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<TofuFoodEntity>> TofuFoodEntity=Entities.register("tofu_food", () -> EntityType.Builder.<TofuFoodEntity>of(TofuFoodEntity::new, MobCategory.MISC).sized(0.3F, 0.3F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"tofu_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<RiceCakeFoodEntity>> RiceCakeFoodEntity=Entities.register("rice_cake_food", () -> EntityType.Builder.<RiceCakeFoodEntity>of(RiceCakeFoodEntity::new, MobCategory.MISC).sized(0.2F, 0.15F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"rice_cake_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<RoastedRiceCakeFoodEntity>> RoastedRiceCakeFoodEntity=Entities.register("roasted_rice_cake_food", () -> EntityType.Builder.<RoastedRiceCakeFoodEntity>of(RoastedRiceCakeFoodEntity::new, MobCategory.MISC).sized(0.2F, 0.2F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"roasted_rice_cake_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<AburaageFoodEntity>> AburaageFoodEntity=Entities.register("abura_age_food", () -> EntityType.Builder.<AburaageFoodEntity>of(AburaageFoodEntity::new, MobCategory.MISC).sized(0.3F, 0.3F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"abura_age_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<KusaDangoFoodEntity>> KusaDangoFoodEntity=Entities.register("kusa_dango_food", () -> EntityType.Builder.<KusaDangoFoodEntity>of(KusaDangoFoodEntity::new, MobCategory.MISC).sized(0.25F, 0.7F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"kusa_dango_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<ColorDangoFoodEntity>> ColorDangoFoodEntity=Entities.register("color_dango_food", () -> EntityType.Builder.<ColorDangoFoodEntity>of(ColorDangoFoodEntity::new, MobCategory.MISC).sized(0.25F, 0.7F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"color_dango_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<MitarashiDangoFoodEntity>> MitarashiDangoFoodEntity=Entities.register("mitarashi_dango_food", () -> EntityType.Builder.<MitarashiDangoFoodEntity>of(MitarashiDangoFoodEntity::new, MobCategory.MISC).sized(0.25F, 0.7F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"mitarashi_dango_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<TsunaSushiFoodEntity>> TsunaSushiFoodEntity=Entities.register("tsuna_sushi_food", () -> EntityType.Builder.<TsunaSushiFoodEntity>of(TsunaSushiFoodEntity::new, MobCategory.MISC).sized(0.55F, 0.55F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"tsuna_sushi_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<SalmonSushiFoodEntity>> SalmonSushiFoodEntity=Entities.register("salmon_sushi_food", () -> EntityType.Builder.<SalmonSushiFoodEntity>of(SalmonSushiFoodEntity::new, MobCategory.MISC).sized(0.55F, 0.55F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"salmon_sushi_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<SquidSushiFoodEntity>> SquidSushiFoodEntity=Entities.register("squid_sushi_food", () -> EntityType.Builder.<SquidSushiFoodEntity>of(SquidSushiFoodEntity::new, MobCategory.MISC).sized(0.55F, 0.55F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"squid_sushi_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<EggSushiFoodEntity>> EggSushiFoodEntity=Entities.register("egg_sushi_food", () -> EntityType.Builder.<EggSushiFoodEntity>of(EggSushiFoodEntity::new, MobCategory.MISC).sized(0.55F, 0.55F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"egg_sushi_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<SalmonRoeSushiFoodEntity>> SalmonRoeSushiFoodEntity=Entities.register("salmon_roe_sushi_food", () -> EntityType.Builder.<SalmonRoeSushiFoodEntity>of(SalmonRoeSushiFoodEntity::new, MobCategory.MISC).sized(0.55F, 0.55F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"salmon_roe_sushi_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<GravelSushiFoodEntity>> GravelSushiFoodEntity=Entities.register("gravel_sushi_food", () -> EntityType.Builder.<GravelSushiFoodEntity>of(GravelSushiFoodEntity::new, MobCategory.MISC).sized(0.55F, 0.55F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"gravel_sushi_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<InariFoodEntity>> InariFoodEntity=Entities.register("inari_food", () -> EntityType.Builder.<InariFoodEntity>of(InariFoodEntity::new, MobCategory.MISC).sized(0.55F, 0.55F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"inari_food").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<KitsunebiEntity>> KitsunebiEntity=Entities.register("kitsunebi", () -> EntityType.Builder.<KitsunebiEntity>of(KitsunebiEntity::new, MobCategory.MISC).sized(0.25F, 0.25F).clientTrackingRange(4).updateInterval(10).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"kitsunebi").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<GhostEntity>> Ghost=Entities.register("ghost", () -> EntityType.Builder.<GhostEntity>of(GhostEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"ghost").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<CushionEntity>> Cushion=Entities.register("cushion", () -> EntityType.Builder.<CushionEntity>of(CushionEntity::new, MobCategory.MISC).sized(0.7F, 0.2F).clientTrackingRange(8).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"butadon_food").toString()));
  //  public static final DeferredHolder<EntityType<?>,EntityType<JufuEntity>> Jufu=Entities.register("jufu", () -> EntityType.Builder.<JufuEntity>of(JufuEntity::new, MobCategory.MISC).sized(0.25F, 0.25F).clientTrackingRange(4).updateInterval(10).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"jufu").toString()));
    public static final DeferredHolder<EntityType<?>,EntityType<JufuEffectDisplayEntity>> JufuEffectDisplay=Entities.register("jufu_effect_display", () -> EntityType.Builder.<JufuEffectDisplayEntity>of(JufuEffectDisplayEntity::new, MobCategory.MISC).sized(0.25F, 0.25F).clientTrackingRange(4).updateInterval(10).build(ResourceLocation.fromNamespaceAndPath(ModCoreUrushi.ModID,"jufu_effect_display").toString()));

    public static void register(IEventBus eventBus) {
        Entities.register(eventBus);
    }

}
